# This is a basic workflow to help you get started with Actions

name: Push on Dev (dry)

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: 
      - dev
      - prod
       

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Create new release
        id: release
        uses: cycjimmy/semantic-release-action@v2
        with:
          semantic_version: 17.3.7
          branches: |    
            [ 
              'master',
              'dev',
              'prod'
            ]
          extra_plugins: |
            @semantic-release/changelog@5
            @semantic-release/git@9
            conventional-changelog-conventionalcommits@4
        env:
          GIT_AUTHOR_NAME: ${{ github.actor }}
          GIT_AUTHOR_EMAIL: ${{ github.actor }}@users.noreply.github.com
          GIT_COMMITTER_NAME: ${{ github.actor }}
          GIT_COMMITTER_EMAIL: ${{ github.actor }}@users.noreply.github.com
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check outputs
        run:
          echo ${{ steps.release.outputs.new_release_version }}
